# Generated by Django 4.2.9 on 2026-09-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_meetingreport_city_nation_meetingreport_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='uploadedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='uploadedat'),
        ),
    ]
